[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --force --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.70.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"